name: travel_tips_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.4.3
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2  
  image_picker: ^0.8.6+4
  json_annotation: ^4.8.0
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/json/